-- MySQL Script generated by MySQL Workbench
-- mar 14 nov 2017 18:41:17 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DB_Banana_Gest
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_Banana_Gest
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_Banana_Gest` DEFAULT CHARACTER SET utf8 ;
USE `DB_Banana_Gest` ;

-- -----------------------------------------------------
-- Table `DB_Banana_Gest`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_Banana_Gest`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `firts_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `code` VARCHAR(15) NULL,
  `area` VARCHAR(45) NULL,
  `active` BINARY(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Banana_Gest`.`proyect`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_Banana_Gest`.`proyect` (
  `id_proyect` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NOT NULL,
  `due_date` DATE NOT NULL,
  `due_time` TIME NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `progress` INT NULL DEFAULT 0,
  PRIMARY KEY (`id_proyect`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Banana_Gest`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_Banana_Gest`.`role` (
  `id_role` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `description` VARCHAR(45) NULL,
  `privileges` VARCHAR(10) NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_role`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Banana_Gest`.`task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_Banana_Gest`.`task` (
  `id_task` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `due_date` DATE NULL,
  `due_time` TIME NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `done` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`id_task`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_Banana_Gest`.`user_has_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_Banana_Gest`.`user_has_role` (
  `user_id_user` INT NOT NULL,
  `role_id_role` INT NOT NULL,
  `proyect_id_proyect` INT NOT NULL,
  `task_id_task` INT NOT NULL,
  `active` VARCHAR(45) NOT NULL DEFAULT '1',
  PRIMARY KEY (`user_id_user`, `role_id_role`, `proyect_id_proyect`, `task_id_task`),
  INDEX `fk_user_has_role_role1_idx` (`role_id_role` ASC),
  INDEX `fk_user_has_role_user_idx` (`user_id_user` ASC),
  INDEX `fk_user_has_role_proyect1_idx` (`proyect_id_proyect` ASC),
  INDEX `fk_user_has_role_task1_idx` (`task_id_task` ASC),
  CONSTRAINT `fk_user_has_role_user`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `DB_Banana_Gest`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_role_role1`
    FOREIGN KEY (`role_id_role`)
    REFERENCES `DB_Banana_Gest`.`role` (`id_role`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_role_proyect1`
    FOREIGN KEY (`proyect_id_proyect`)
    REFERENCES `DB_Banana_Gest`.`proyect` (`id_proyect`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_role_task1`
    FOREIGN KEY (`task_id_task`)
    REFERENCES `DB_Banana_Gest`.`task` (`id_task`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
